lms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from students.views import get_random, hello


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('hello/', hello, name='hello'),
    path('password/', get_random, name='password'),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

students/urls.py
from django.urls import path

from students.views import StudentCreateView, StudentDeleteView, StudentListView, StudentUpdateView, generate_students
app_name = 'students'

urlpatterns = [
    path('', StudentListView.as_view(), name='list'),
    path('create/', StudentCreateView.as_view(), name='create'),
    path('generate-students/', generate_students, name='generate'),
    path('edit/<uuid:uuid>', StudentUpdateView.as_view(), name='edit'),
    path('delete/<uuid:uuid>', StudentDeleteView.as_view(), name='delete'),
]

students/models.py
import uuid

from core.models import Person

from django.db import models

from groups.models import Group


class Student(Person):
    rating = models.SmallIntegerField(null=True, default=0)
    email = models.EmailField(null=True, max_length=128)
    phone_number = models.CharField(max_length=20, null=True, blank=True)
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    group = models.ForeignKey(
        to=Group,
        null=True,
        on_delete=models.SET_NULL,
        related_name='students'
    )

    def __str__(self):
        return f'{super().__str__()}, {self.rating}'

students/forms.py
from django import forms
from django.core.exceptions import ValidationError

from students.models import Student


class StudentCreateForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['first_name', 'last_name', 'rating', 'email', 'phone_number', 'group']

    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']
        if not phone_number.isnumeric():
            raise ValidationError('value error: phone number must be digits')
        return phone_number

students/views.py
from core.utils import gen_password, gen_student, parse_length, parse_length_count

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponse, HttpResponseBadRequest
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from .forms import StudentCreateForm
from .models import Student


def hello(request):
    return HttpResponse('Hello from Django!')


def get_random(request):
    try:
        length = parse_length(request, 10)
    except Exception as ex:
        return HttpResponse(str(ex), status_code=400)

    result = gen_password(length)

    return HttpResponse(result)


def generate_students(request):
    count = request.GET.get('count')
    if count is None:
        return HttpResponseBadRequest("count - required parameter")

    try:
        count = parse_length_count(count)
    except Exception as ex:
        return HttpResponseBadRequest(str(ex))

    for _ in range(count):
        student = gen_student()
        st = Student(**student)
        st.save()

    return HttpResponse(f'added {count} students')


class StudentListView(ListView):
    model = Student
    template_name = 'students-list.html'
    context_object_name = 'students'
    paginate_by = 10

    def get_queryset(self):
        students = super().get_queryset().select_related('group').all()
        request = self.request

        first_name = request.GET.get('first_name')
        last_name = request.GET.get('last_name')
        rating = request.GET.get('rating')

        if first_name:
            or_names = first_name.split('|')
            or_cond = Q()
            for or_name in or_names:
                or_cond = or_cond | Q(first_name=or_name)
            students = students.filter(or_cond)

        if last_name:
            students = students.filter(last_name=last_name)

        if rating:
            students = students.filter(rating=rating)

        return students


class StudentCreateView(LoginRequiredMixin, CreateView):
    model = Student
    form_class = StudentCreateForm
    template_name = 'students-create.html'
    success_url = reverse_lazy('students:list')


class StudentUpdateView(LoginRequiredMixin, UpdateView):
    model = Student
    form_class = StudentCreateForm
    template_name = 'students-edit.html'
    context_object_name = 'student'
    success_url = reverse_lazy('students:list')
    pk_url_kwarg = 'uuid'


class StudentDeleteView(LoginRequiredMixin, DeleteView):
    model = Student
    success_url = reverse_lazy('students:list')
    pk_url_kwarg = 'uuid'

students/templates/students-create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title%}
    <title>Create student</title>
{% endblock %}

{% block header%}
<h3>Create student</h3>
{% endblock %}

{% block content %}
    <form method="post">

        {% csrf_token %}

        {{form|crispy}}

        <input type="submit" class="btn btn-success" value="Create">
    </form>
{% endblock %}

students/templates/students-edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title%}
    <title>Edit student</title>
{% endblock %}

{% block header%}
<h3>Students edit</h3>
{% endblock %}

{% block content %}

    <form method="post">

        {% csrf_token %}

        {{form|crispy}}

        <input type="submit" class="btn btn-success" value="Edit">
        <input formaction="{% url 'students:delete' student.uuid %}" type="submit" class="btn btn-danger" value="Delete">
    </form>

{% endblock %}

students/templates/students-list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title%}
    <title>Students list</title>
{% endblock %}

{% block header%}
<h3>Students list</h3>
{% endblock %}

{% block content %}
<form>
    <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text">First name:</span>
            </div>
        <input name="first_name" type="text" class="form-control" placeholder="Enter first name:" aria-label="Username" aria-describedby="basic-addon1">
    </div>

    <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text">First name:</span>
            </div>
        <input name="last_name" type="text" class="form-control" placeholder="Enter last name:" aria-label="Username" aria-describedby="basic-addon1">
    </div>
    <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text">Rating:</span>
            </div>
        <input name="rating" type="text" class="form-control" placeholder="Enter rating:" aria-label="Username" aria-describedby="basic-addon1">
    </div>

    <input class="btn btn-info" type="submit" value="Search">
</form><br>



<h3><a href="{% url 'students:create' %}">Create student</a></h3><br>

{% include 'includes/students-table.html' %}

{% endblock %}