groups/urls.py
from django.urls import path

from groups.views import GroupCreateView, GroupDeleteView, GroupListView, GroupUpdateView, generate_groups

app_name = 'groups'

urlpatterns = [
    path('', GroupListView.as_view(), name='list'),
    path('create/', GroupCreateView.as_view(), name='create'),
    path('edit/<int:id>', GroupUpdateView.as_view(), name='edit'),
    path('delete/<int:id>', GroupDeleteView.as_view(), name='delete'),
    path('gen_group', generate_groups, name='gen_group'),
]

lms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from students.views import get_random, hello


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('hello/', hello, name='hello'),
    path('password/', get_random, name='password'),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

groups/models.py
import random

from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from faker import Faker

from teachers.models import Teacher


class Classroom(models.Model):
    name = models.CharField(max_length=32)
    floor = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(2), MaxValueValidator(6)]
    )

    def __str__(self):
        return f'{self.name}, {self.floor}'


class Group(models.Model):
    name = models.CharField(max_length=64, null=False)
    group_type = models.CharField(max_length=64, null=False) # noqa
    teacher = models.ForeignKey(
        to=Teacher,
        null=True,
        on_delete=models.SET_NULL,
        related_name='groups'
    )
    head = models.OneToOneField(
        to='students.Student',
        null=True,
        on_delete=models.SET_NULL,
        related_name='head_of_group'
    )
    classrooms = models.ManyToManyField(
        to=Classroom,
        related_name='groups'
    )

    def __str__(self):
        return self.name

    @staticmethod
    def gen_group(teachers_list):
        fake = Faker()
        Group.objects.create(
            name=fake.random_int(min=0, max=100),
            type=fake.random_int(min=0, max=100),
            teacher=random.choice(teachers_list)
        )

    def clean(self):
        from students.models import Student
        st = Student.objects.get(uuid=self.head.uuid)
        if self.pk != st.group.id:
            raise ValidationError('The head must be in the group')

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

groups/forms.py
from django import forms

from groups.models import Group


class GroupCreateForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = '__all__'

groups/views.py
from core.utils import parse_length_count

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponse, HttpResponseBadRequest
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from groups.forms import GroupCreateForm
from groups.models import Group

from teachers.models import Teacher


def generate_groups(request):
    count = request.GET.get('count')
    if count is None:
        return HttpResponseBadRequest("count - required parameter")

    try:
        count = parse_length_count(count)
    except Exception as ex:
        return HttpResponseBadRequest(str(ex))

    teachers_list = list(Teacher.objects.all())
    for _ in range(count):
        Group.gen_group(teachers_list)

    return HttpResponse(f'added {count} groups')


class GroupListView(ListView):
    model = Group
    template_name = 'groups-list.html'
    context_object_name = 'groups'
    paginate_by = 10

    def get_queryset(self):
        groups = super().get_queryset().select_related('teacher').all()
        request = self.request

        name = request.GET.get('name')
        group_type = request.GET.get('group_type')

        if name:
            or_names = name.split('|')
            or_cond = Q()
            for or_name in or_names:
                or_cond = or_cond | Q(name=or_name)
            groups = groups.filter(or_cond)

        if group_type:
            groups = groups.filter(group_type=group_type)

        return groups


class GroupCreateView(LoginRequiredMixin, CreateView):
    model = Group
    form_class = GroupCreateForm
    template_name = 'groups-create.html'
    success_url = reverse_lazy('groups:list')


class GroupUpdateView(LoginRequiredMixin, UpdateView):
    model = Group
    form_class = GroupCreateForm
    template_name = 'groups-edit.html'
    context_object_name = 'group'
    success_url = reverse_lazy('groups:list')
    pk_url_kwarg = 'id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['students'] = self.get_object().students.all()
        return context


class GroupDeleteView(LoginRequiredMixin, DeleteView):
    model = Group
    success_url = reverse_lazy('groups:list')
    pk_url_kwarg = 'id'

groups/templates/groups-create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title%}
    <title>Create group</title>
{% endblock %}


{% block header%}
<h3>Create group</h3>
{% endblock %}

{% block content %}
    <form method="post">

        {% csrf_token %}

        {{form|crispy}}

        <input type="submit" class="btn btn-success" value="Create">
    </form>

{% endblock %}

groups/templates/groups-edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title%}
    <title>Edit group</title>
{% endblock %}

{% block header%}
<h3>Groups edit</h3>
{% endblock %}

{% block content %}

    <form method="post">

        {% csrf_token %}

        {{form|crispy}}

        <input type="submit" class="btn btn-success" value="Edit">
        <input formaction="{% url 'groups:delete' group.id %}" type="submit" class="btn btn-danger" value="Delete">
    </form>
<br>

<h3>Teacher:</h3>

{{ group.teacher }}

<h3>Students:</h3>

{% include 'includes/students-table.html' %}

{% endblock %}

groups/templates/groups-list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title%}
    <title>Groups list</title>
{% endblock %}

{% block header%}
<h3>Groups list</h3>
{% endblock %}

{% block content %}

<form>
<div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text">Group name:</span>
        </div>
    <input name="name" type="text" class="form-control" placeholder="Enter group name:" aria-label="Username" aria-describedby="basic-addon1">
</div>

<div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text">Group type:</span>
        </div>
    <input name="group_type" type="text" class="form-control" placeholder="Enter group type::" aria-label="Username" aria-describedby="basic-addon1">
</div>

<input class="btn btn-info" type="submit" value="Search">

</form><br>

<h3><a href="{% url 'groups:create' %}">Create group</a></h3><br>

{% include 'includes/groups-table.html' %}

{% endblock %}