lms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from students.views import get_random, hello


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('hello/', hello, name='hello'),
    path('password/', get_random, name='password'),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

teachers/urls.py
from django.urls import path

from teachers.views import TeacherCreateView, TeacherDeleteView, TeacherListView, TeacherUpdateView

app_name = 'teachers'

urlpatterns = [
    path('', TeacherListView.as_view(), name='list'),
    path('create/', TeacherCreateView.as_view(), name='create'),
    path('edit/<int:id>', TeacherUpdateView.as_view(), name='edit'),
    path('delete/<int:id>', TeacherDeleteView.as_view(), name='delete'),
]

teachers/models.py
from core.models import Person

from django.db import models

from faker import Faker


class Teacher(Person):
    specialization = models.CharField(max_length=64, null=True)

    def __str__(self):
        return f'{super().__str__()}, {self.specialization}'

    @staticmethod
    def gen_teacher():
        fake = Faker()
        Teacher.objects.create(
            firstname=fake.first_name(),
            lastname=fake.last_name(),
            birthdate=fake.date(),
        )

teachers/forms.py
from django import forms

from teachers.models import Teacher


class TeacherCreateForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = ['first_name', 'last_name']

teachers/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from .forms import TeacherCreateForm
from .models import Teacher


class TeacherListView(ListView):
    model = Teacher
    template_name = 'teachers-list.html'
    context_object_name = 'teachers'
    paginate_by = 10

    def get_queryset(self):
        teachers = super().get_queryset()
        request = self.request
        first_name = request.GET.get('first_name')
        last_name = request.GET.get('last_name')

        if first_name:
            or_names = first_name.split('|')
            or_cond = Q()
            for or_name in or_names:
                or_cond = or_cond | Q(first_name=or_name)
            teachers = teachers.filter(or_cond)

        if last_name:
            teachers = teachers.filter(last_name=last_name)

        return teachers


class TeacherCreateView(LoginRequiredMixin, CreateView):
    model = Teacher
    form_class = TeacherCreateForm
    template_name = 'teachers-create.html'
    success_url = reverse_lazy('teachers:list')


class TeacherUpdateView(LoginRequiredMixin, UpdateView):
    model = Teacher
    form_class = TeacherCreateForm
    template_name = 'teachers-edit.html'
    context_object_name = 'teacher'
    success_url = reverse_lazy('teachers:list')
    pk_url_kwarg = 'id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['groups'] = self.get_object().groups.all()
        return context


class TeacherDeleteView(LoginRequiredMixin, DeleteView):
    model = Teacher
    success_url = reverse_lazy('teachers:list')
    pk_url_kwarg = 'id'

teachers/templates/teachers-create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title%}
    <title>Create teacher</title>
{% endblock %}

{% block header%}
<h3>Create teacher</h3>
{% endblock %}

{% block content %}
    <form method="post">

        {% csrf_token %}

        {{form|crispy}}

        <input type="submit" class="btn btn-success" value="Create">
    </form>

{% endblock %}

teachers/templates/teachers-edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title%}
    <title>Edit teacher</title>
{% endblock %}

{% block header%}
<h3>Teachers edit</h3>
{% endblock %}

{% block content %}

    <form method="post">

        {% csrf_token %}

        {{form|crispy}}

        <input type="submit" class="btn btn-success" value="Edit">
        <input formaction="{% url 'teachers:delete' teacher.id %}" type="submit" class="btn btn-danger" value="Delete">
    </form><br>

{% include 'includes/groups-table.html' %}

{% endblock %}

teachers/templates/teachers-list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title%}
    <title>Teachers list</title>
{% endblock %}

{% block header%}
<h3>Teachers list</h3>
{% endblock %}

{% block content %}
<form>
<div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text">First name:</span>
        </div>
    <input name="first_name" type="text" class="form-control" placeholder="Enter first name:" aria-label="Username" aria-describedby="basic-addon1">
</div>

<div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text">First name:</span>
        </div>
    <input name="last_name" type="text" class="form-control" placeholder="Enter last name:" aria-label="Username" aria-describedby="basic-addon1">
</div>

<input class="btn btn-info" type="submit" value="Search">

</form><br>

<h3><a href="{% url 'teachers:create' %}">Create teacher</a></h3><br>

<table>
        <tr>
            <th>id</th>
            <th>firstname</th>
            <th>lastname</th>
            <th>group</th>
            <th>edit teacher</th>
            <th>delete teacher</th>
        </tr>
    {% for teacher in teachers %}
        <tr>
            <td>{{ teacher.id }}</td>
            <td>{{ teacher.first_name }}</td>
            <td>{{ teacher.last_name }}</td>
            <td>{{ teacher.group.name }}</td>
            <td><a href="{% url 'teachers:edit' teacher.id %}">EDIT</a></td>
            <td><form method="POST" action="{% url 'teachers:delete' teacher.id %}">
               {% csrf_token %}<input type="submit" value="DELETE">
            </form></td>
        </tr>
    {% endfor %}
</table>

{% include 'includes/page-navigation.html' %}

{% endblock %}