accounts/urls.py
from accounts.views import AccountCreateView, AccountLoginView, AccountLogoutView, AccountPasswordChangeView, \
    AccountUpdateView

from django.urls import path


app_name = 'accounts'

urlpatterns = [
    path('register/', AccountCreateView.as_view(), name='register'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', AccountUpdateView.as_view(), name='profile'),
    path('password/', AccountPasswordChangeView.as_view(), name='password'),
    ]

core/urls.py
from core.views import index

from django.urls import path

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    ]

groups/urls.py
from django.urls import path

from groups.views import GroupCreateView, GroupDeleteView, GroupListView, GroupUpdateView, generate_groups

app_name = 'groups'

urlpatterns = [
    path('', GroupListView.as_view(), name='list'),
    path('create/', GroupCreateView.as_view(), name='create'),
    path('edit/<int:id>', GroupUpdateView.as_view(), name='edit'),
    path('delete/<int:id>', GroupDeleteView.as_view(), name='delete'),
    path('gen_group', generate_groups, name='gen_group'),
]

lms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from students.views import get_random, hello


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('hello/', hello, name='hello'),
    path('password/', get_random, name='password'),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

students/urls.py
from django.urls import path

from students.views import StudentCreateView, StudentDeleteView, StudentListView, StudentUpdateView, generate_students
app_name = 'students'

urlpatterns = [
    path('', StudentListView.as_view(), name='list'),
    path('create/', StudentCreateView.as_view(), name='create'),
    path('generate-students/', generate_students, name='generate'),
    path('edit/<uuid:uuid>', StudentUpdateView.as_view(), name='edit'),
    path('delete/<uuid:uuid>', StudentDeleteView.as_view(), name='delete'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

{% block title%}
    <title>LMS</title>
{% endblock %}
<style>

table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'core:index' %}">LMS</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'students:list' %}">Students <span class="sr-only">(current)</span></a>
          </li>
            <li class="nav-item active">
            <a class="nav-link" href="{% url 'teachers:list' %}">Teachers <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'groups:list' %}">Groups</a>
          </li>
    <!--      <li class="nav-item dropdown">-->
    <!--        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
    <!--          Dropdown-->
    <!--        </a>-->
    <!--        <div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
    <!--          <a class="dropdown-item" href="#">Action</a>-->
    <!--          <a class="dropdown-item" href="#">Another action</a>-->
    <!--          <div class="dropdown-divider"></div>-->
    <!--          <a class="dropdown-item" href="#">Something else here</a>-->
    <!--        </div>-->
    <!--      </li>-->
    <!--      <li class="nav-item">-->
    <!--        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>-->
    <!--      </li>-->
        </ul>
    <!--    <form class="form-inline my-2 my-lg-0">-->
    <!--      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
    <!--      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
    <!--    </form>-->
            <ul class="navbar-nav ">

                {% if user.is_authenticated %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:profile' %}">Profile ({{ user.username }})</a>
                </li>
                <li class="img-circle.vert">
                    <img class="rounded-circle p-1 m-1" width="40" height="40" src=" {{ user.profile.image.url }} ">
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Log out</a>
                </li>

                {% else %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                </li>

                {% endif %}

            </ul>
      </div>
    </div>
</nav>
</div>

{% include 'includes/messages.html' %}

<div class="container">
    <div class="border border-white rounded-pill shadow p-3 mb-5 mt-5 bg-white rounded text-center">
        {% block header %}
            <h3>Welcome to LMS</h3>
        {% endblock %}
    </div>

    {% block content %}
    {% endblock %}
</div>

</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h4><a href="{% url 'students:list' %}">Students list</a></h4>
    <h4><a href="{% url 'teachers:list' %}">Teachers list</a></h4>
    <h4><a href="{% url 'groups:list' %}">Groups list</a></h4>
{% endblock %}